name: PAM-Vault-Lab CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black pylint

    - name: Lint with flake8
      run: |
        # Stop build if there are Python syntax errors or undefined names
        flake8 automation/python --count --select=E9,F63,F7,F82 --show-source --statistics
        # Exit-zero treats all errors as warnings
        flake8 automation/python --count --exit-zero --max-complexity=10 --max-line-length=100 --statistics

    - name: Check formatting with black
      run: |
        black --check automation/python

  test:
    name: Run Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: vaultadmin
          POSTGRES_PASSWORD: vaultpass123
          POSTGRES_DB: testdb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: rootpass123
          MYSQL_DATABASE: testdb
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        ports:
          - 3306:3306

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r automation/python/requirements.txt

    - name: Start Vault in dev mode
      run: |
        docker run -d --name vault \
          --cap-add=IPC_LOCK \
          -e VAULT_DEV_ROOT_TOKEN_ID=root-token-change-me \
          -e VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200 \
          -p 8200:8200 \
          hashicorp/vault:1.15 server -dev

        # Wait for Vault to be ready
        sleep 5

    - name: Run tests
      env:
        VAULT_ADDR: http://localhost:8200
        VAULT_TOKEN: root-token-change-me
      run: |
        pytest tests/ -v --tb=short

  docker-compose:
    name: Test Docker Compose
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create .env file
      run: |
        cp .env.example .env

    - name: Start services
      run: |
        docker-compose up -d

    - name: Wait for services
      run: |
        sleep 30

    - name: Check service health
      run: |
        docker-compose ps
        docker-compose logs vault

    - name: Test Vault connectivity
      run: |
        curl -f http://localhost:8200/v1/sys/health || exit 1

    - name: Test PostgreSQL connectivity
      run: |
        docker exec $(docker-compose ps -q postgres) pg_isready -U vaultadmin

    - name: Test MySQL connectivity
      run: |
        docker exec $(docker-compose ps -q mysql) mysqladmin ping -h localhost -u root -prootpass123

    - name: Cleanup
      if: always()
      run: |
        docker-compose down -v

  validate-yaml:
    name: Validate YAML Files
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Validate docker-compose.yml
      run: |
        docker-compose config

    - name: Validate Ansible files
      run: |
        pip install ansible-core
        ansible-lint automation/ansible/playbooks/*.yml || true

  documentation:
    name: Check Documentation
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Check for broken links in markdown
      uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
        config-file: '.github/markdown-link-check-config.json'
        base-branch: 'main'

    - name: Validate markdown formatting
      run: |
        npm install -g markdownlint-cli
        markdownlint '**/*.md' --ignore node_modules || true

  security:
    name: Security Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: Upload Trivy results to GitHub Security
      uses: github/codeql-action/upload-sarif@v2
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'
